### ISSUE TITLE
Problem: developers do not leave reference from Problem to Goal

### ISSUE THREAD

**Issue by zolotokrylin** [clearpool-finance/developers#1]
> @clearpool-finance/team-usdx ,
In sub-issues, remember to reference a parent issue, otherwise, it doesn't display in the activity feed of the parent issue.

```
// convention
sub of: <parent_issue>
```

_Originally posted by @zolotokrylin in https://github.com/clearpool-finance/usdx/issues/1#issuecomment-2088048151_

**Comment by zolotokrylin** [comment]
@Fils7 could you please take this problem and resolve it by Friday. No rush. Thanks

**Comment by Fils7** [comment]
Hey @zolotokrylin , I'm trying to push a local branch to this repo and it shows access denied.

**Comment by georgeciubotaru** [comment]
@Fils7 Check now
